[workspace]
members = [
    "modules/calca",
    "modules/cjls",
    "modules/cjsyntax",
    "modules/cjtoml",
    "modules/ginkgo",
    "modules/index_map",
    "modules/jsonrpc",
    "modules/lsp_codegen",
    "modules/rope",
    "modules/stdxx",
]
build-members = []
test-members = []
compile-option = "-Woff unused -O2"
override-compile-option = ""
link-option = ""
target-dir = ""
script-dir = ""

[dependencies]

# [target.x86_64-unknown-linux-gnu.bin-dependencies]
# path-option = ["third_party/stdx"]

[target.aarch64-apple-darwin.bin-dependencies]
# TODO: platform-specific stdx path
path-option = ["${CANGJIE_HOME}/third_party/stdx/static/stdx"]

# [target.x86_64-w64-mingw32.bin-dependencies]
# path-option = ["third_party/stdx"]
