[workspace]
members = ["modules/cjls", "modules/lsp", "modules/stdxx"]
build-members = []
test-members = []
compile-option = ""
override-compile-option = ""
link-option = ""
target-dir = ""
script-dir = ""

[dependencies]

[target.x86_64-unknown-linux-gnu.bin-dependencies]
path-option = ["third_party/stdx"]

[target.aarch64-apple-darwin.bin-dependencies]
path-option = ["third_party/stdx"]
