[general]
output-subpackage = "lsp_types"
imports = [
    "std.collection.*",
    "std.deriving.*",
    "stdx.serialization.serialization.*",
    "stdxx.*",
    "stdxx.deriving.*",
    "jsonrpc.*",
]

[types.URI]
alias = "String"

[types.DocumentUri]
alias = "String"

[types.LSPAny]
alias = "AnyValue"

[types.ProgressToken]
alias = "IntegerOrString"

[types.ErrorCodes]
alias = "ErrorCode"

[types.LSPErrorCodes]
extern = "ErrorCode"
