[package]
cjc-version = "1.3.0"
name = "lsp_codegen"
organization = ""
description = "nothing here"
version = "1.0.0"
target-dir = ""
script-dir = ""
output-type = "executable"
compile-option = ""
override-compile-option = ""
link-option = "-lc++"
package-configuration = {}

[dependencies]
stdxx = { path = "../stdxx" }
